### ISSUE TITLE
following the instructions, my client could not connect

### ISSUE THREAD

**Issue by titimoby** [AdventuresInMinecraft/AdventuresInMinecraft-Linux#1]
I followed the steps described and the server looks like running good.
I then followed the instructions from my "Apprendre à coder grâce à Minecraft" first chapter and launched a profile form 1.6.4
I can't connect either to localhost or 127.0.0.1, the message is:
```
Connection Lost
End of stream
```

**Comment by titimoby** [comment]
I identified 2 ports used by the minecraft server, so I tried to connect to those.
First one was localhost:4711
Client got a connection lost with 
`Internal Exception : java.net.SocketTimeOutException: Read Timed Out`

Server got errors in logs:
```
[11:49:16 INFO]: [RaspberryJuice] Starting input thread
[11:49:16 INFO]: [RaspberryJuice] Starting output thread!
[11:49:16 INFO]: [RaspberryJuice] Opened connection to/127.0.0.1:55282.
[11:49:46 WARN]: [RaspberryJuice] Task #2 for RaspberryJuice v1.10 generated an exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_144]
	at net.zhuoweizhang.raspberryjuice.RemoteSession.handleLine(RemoteSession.java:129) ~[?:?]
	at net.zhuoweizhang.raspberryjuice.RemoteSession.tick(RemoteSession.java:113) ~[?:?]
	at net.zhuoweizhang.raspberryjuice.RaspberryJuicePlugin$TickHandler.run(RaspberryJuicePlugin.java:197) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit.jar:git-Bukkit-876d22c]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit.jar:git-Bukkit-876d22c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [craftbukkit.jar:git-Bukkit-876d22c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit.jar:git-Bukkit-876d22c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit.jar:git-Bukkit-876d22c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit.jar:git-Bukkit-876d22c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[11:49:46 INFO]: [RaspberryJuice] Closed connection to/127.0.0.1:55282.

```

The second one was 15131 and client got:
```
Failed to connect to the server
Connection refused (Connection refused)
```
and no log on server for this one (maybe a wrong port identification from me)

**Comment by titimoby** [comment]
When I tried with minecraft 1.8.4, the server i got the multiplayer.disconnect.outdated_client.
So of course, this was the underlying issue : I created a profile from Minecraft client launcher with the latest version (1.12.1) which correspond to the craftbukkit.jar version build .

**Comment by martinohanlon** [comment]
The Linux Starter Kit is for use with the 2nd Edition of Adventures in Minecraft (which is yet to be released) - you should be using Minecraft version 1.12.

Fyi - Linux isnt officially supported by Adventures in Minecraft, I am supplying the Starter Kit on a best endeavours basis.

**Comment by titimoby** [comment]
No problem, in the end. But as for the 1st edition, using the OSX kit with just movind command files to shell scripts was very reliable for Linux.
Don't be shy, your work is perfect on Linux too.

**Comment by martinohanlon** [comment]
The challenge with providing a Starter Kit for Linux is the large number of distributions and providing a set of instructions which can be followed consistently.
